title: Eric J. Smith
description: Eric J. Smith's personal website
username: Eric J. Smith
user_title: Detail oriented full stack developer and entrepreneur
email: eric@ericjsmith.com

google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
